"""
Export: the corrected spec, for whoever comes next.

The agent spent calls learning what this tool really does. That knowledge
should not be trapped in one agent's memory file. Export compiles confirmed
beliefs into two artifacts:

  TOOLS.md   a corrected specification, doc claim beside observed reality,
             with the evidence that settled it
  guards     the same beliefs as executable enforcement

Anthropic's "writing tools for agents" argues good tool definitions are the
highest-leverage thing you can give an agent. This produces one empirically,
from failures, rather than from a spec author's optimism.
"""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

from agent.beliefs import BeliefStore, Status
from shim.guards import REGISTRY, compile_guards

HEADER = """# {tool} -- corrected specification

Generated by skeptic on {when} from {n_confirmed} confirmed beliefs.

The published documentation for this tool is wrong in the ways listed below.
Each entry was established by an experiment, not by assumption: the probe
that settled it is named, and predictions were committed before the
experiment ran.

Read this instead of the vendor docs, or load the accompanying guards and
have them enforced for you.

"""

ENTRY = """## {title}
{warning}

**The docs say:** {doc_claims}

**Actually:** {belief}

**Do this:** {action}

| | |
| --- | --- |
| class | `{cls}` |
| operation | `{operation}` |
| parameter | `{parameter}` |
| confidence | P(docs correct) = {p_doc:.2f} after {n_obs} observations |
| settled by | {probes} |
| survived falsification | {survived} |

"""

FOOTER = """---

## What is NOT claimed

Anything absent from this list was either never observed to misbehave or was
observed but never settled by an experiment. Absence here is not a promise
that the docs are right about it.

{unsettled}
"""


def to_markdown(store: BeliefStore) -> str:
    confirmed = store.active()
    out = [HEADER.format(
        tool=store.tool,
        when=time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
        n_confirmed=len(confirmed),
    )]

    by_class: dict[str, list[Any]] = {}
    for b in confirmed:
        by_class.setdefault(b.cls, []).append(b)

    for cls_name in sorted(by_class):
        out.append(f"\n# {cls_name.replace('_', ' ')}\n")
        for b in by_class[cls_name]:
            title = f"`{b.operation}`" + (f" / `{b.parameter}`" if b.parameter else "")
            # A belief an adversary objected to, and which has not since been
            # re-settled, is still published (withholding it would be its own
            # kind of lie) but it is labelled. A corrected spec that quietly
            # includes claims a reviewer already dismantled is not corrected.
            objection = next(
                (h.get("detail") for h in reversed(b.history)
                 if h.get("event") == "adversary_objection"), None
            )
            warning = ""
            if objection and not b.survived_falsification:
                warning = (
                    f"\n> **Contested.** An adversarial reviewer objected to this "
                    f"entry and it has not been re-settled since: {objection}\n"
                )
            out.append(ENTRY.format(
                title=title,
                warning=warning,
                doc_claims=b.doc_claims or "(nothing specific)",
                belief=b.belief,
                action=b.action or "(no action recorded)",
                cls=b.cls,
                operation=b.operation,
                parameter=b.parameter or "-",
                p_doc=b.posterior.p_doc_correct,
                n_obs=b.evidence_for + b.evidence_against,
                probes=", ".join(f"`{p}`" for p in b.probes) or "-",
                survived=f"`{b.survived_falsification}`" if b.survived_falsification else "not yet challenged",
            ))

    open_h = [b for b in store.ordered() if b.status is Status.HYPOTHESIS]
    unsettled = "\n".join(f"- unsettled: {b.belief}" for b in open_h) or "- (no open hypotheses)"
    out.append(FOOTER.format(unsettled=unsettled))
    return "".join(out)


def manifest(store: BeliefStore) -> dict[str, Any]:
    guards = compile_guards(store)
    return {
        "tool": store.tool,
        "generated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "confirmed_beliefs": len(store.active()),
        "guards": [
            {"name": g.name, "implements": g.implements_class,
             "parameter": g.parameter, "because": g.note}
            for g in guards
        ],
        "unimplemented_classes": sorted(
            {b.cls for b in store.active()} - {c for c, _, _, _ in REGISTRY}
        ),
    }


def export(store: BeliefStore, out_dir: str | Path = "export") -> dict[str, Path]:
    d = Path(out_dir)
    d.mkdir(parents=True, exist_ok=True)
    md = d / "TOOLS.md"
    mf = d / "guards.json"
    md.write_text(to_markdown(store))
    mf.write_text(json.dumps(manifest(store), indent=2))
    return {"markdown": md, "manifest": mf}


if __name__ == "__main__":
    import sys

    s = BeliefStore("lab")
    paths = export(s)
    print(f"  {len(s.active())} confirmed beliefs ->")
    for k, v in paths.items():
        print(f"    {k}: {v} ({v.stat().st_size} bytes)")
    sys.exit(0)
